# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='Status')),
                ('status_date', models.DateTimeField(blank=True, null=True, verbose_name='Status date')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('email',),
            },
        ),
    ]
