# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_auto_20170411_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('facebook_link', models.URLField(verbose_name='Facebook link')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Number')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('event', models.ManyToManyField(blank=True, related_name='event_post', to='blog.BlogPost')),
                ('featured', models.ManyToManyField(blank=True, related_name='featured_post', to='blog.BlogPost')),
                ('in_the_media', models.ManyToManyField(blank=True, related_name='in_the_media_post', to='blog.BlogPost')),
                ('opportunity', models.ManyToManyField(blank=True, related_name='opportunity_post', to='blog.BlogPost')),
                ('publication', models.ManyToManyField(blank=True, related_name='publication_post', to='blog.BlogPost')),
                ('streaming', models.ManyToManyField(blank=True, related_name='streaming_post', to='blog.BlogPost')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='Status')),
                ('status_date', models.DateTimeField(blank=True, null=True, verbose_name='Status date')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('email',),
            },
        ),
        migrations.AddField(
            model_name='facebookhighlight',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Newsletter'),
        ),
    ]
