# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170411_0504'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Number')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('event', models.ManyToManyField(blank=True, related_name='event_post', to='blog.BlogPost')),
                ('featured', models.ManyToManyField(blank=True, related_name='featured_post', to='blog.BlogPost')),
                ('in_the_media', models.ManyToManyField(blank=True, related_name='in_the_media_post', to='blog.BlogPost')),
                ('opportunity', models.ManyToManyField(blank=True, related_name='opportunity_post', to='blog.BlogPost')),
                ('publication', models.ManyToManyField(blank=True, related_name='publication_post', to='blog.BlogPost')),
                ('streaming', models.ManyToManyField(blank=True, related_name='streaming_post', to='blog.BlogPost')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ('number',),
            },
        ),
    ]
