# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('facebook_link', models.URLField(verbose_name='Facebook link')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Newsletter')),
            ],
        ),
    ]
