# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cpf', models.CharField(blank=True, max_length=15, unique=True, verbose_name='CPF')),
                ('passport', models.CharField(blank=True, max_length=50, verbose_name='Passport / RNE')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='Mobile phone')),
            ],
            options={
                'verbose_name': 'Postdoc',
                'verbose_name_plural': 'Postdocs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('affiliation', models.CharField(max_length=255, verbose_name='Affiliation')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('postdoc_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Postdoc')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researchers',
                'ordering': ('name',),
            },
        ),
    ]
