# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-01 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdoc',
            options={'ordering': ('-date',), 'verbose_name': 'Postdoc', 'verbose_name_plural': 'Postdocs'},
        ),
    ]
