# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-11 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_featurecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Swipper Card',
                'verbose_name_plural': 'Swipper Cards',
                'ordering': ('title',),
            },
        ),
    ]
