# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-11 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_swipercard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecard',
            name='image',
        ),
    ]
