# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-07 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroCineMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('youtube_link', models.CharField(max_length=255, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'NeuroCineMat',
                'verbose_name_plural': 'Videos',
                'ordering': ('title',),
            },
        ),
    ]
