# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-07 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_neurocinemat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neurocinemat',
            options={'ordering': ('title',), 'verbose_name': 'NeuroCineMat', 'verbose_name_plural': 'NeuroCineMat Videos'},
        ),
    ]
